name: Build, Test, Package and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev wget gnupg dpkg-dev

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --verbose

      - name: Create deb package
        run: |
          PACKAGE_NAME="logger_app"
          VERSION="1.0"
          ARCH="amd64"

          mkdir -p ${PACKAGE_NAME}_${VERSION}_${ARCH}/DEBIAN
          cat > ${PACKAGE_NAME}_${VERSION}_${ARCH}/DEBIAN/control << EOF
Package: ${PACKAGE_NAME}
Version: ${VERSION}
Section: base
Priority: optional
Architecture: ${ARCH}
Maintainer: Your Name <your.email@example.com>
Description: Simple logger application
Depends: libc6
EOF

          mkdir -p ${PACKAGE_NAME}_${VERSION}_${ARCH}/usr/bin/
          cp build/logger_app ${PACKAGE_NAME}_${VERSION}_${ARCH}/usr/bin/

          dpkg-deb --build ${PACKAGE_NAME}_${VERSION}_${ARCH} ${PACKAGE_NAME}_${VERSION}_${ARCH}.deb

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Automatically created release for commit ${{ github.sha }}.
          draft: false
          prerelease: false

      - name: Upload deb package as a release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: logger_app_1.0_amd64.deb
          asset_name: logger_app_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
