name: Build, Test, Package and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev wget gnupg dpkg-dev

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --verbose

      - name: Create deb package
        run: |
          mkdir -p logger_deb_package/DEBIAN
          cat > logger_deb_package/DEBIAN/control << EOF
          Package: logger-app
          Version: 1.0
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: Simple logger application
          Depends: libc6
          EOF

          mkdir -p logger_deb_package/usr/bin/
          cp build/logger_app logger_deb_package/usr/bin/

          dpkg-deb --build logger_deb_package logger_app.deb

      - name: Upload deb package as a release asset
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          files: logger_app.deb
          generateReleaseNotes: true
